FROM openjdk:8-jre-slim

RUN apt-get update && \
    apt-get install -y procps binutils vim curl && \
    apt-get clean

COPY startup.sh /startup.sh

# appdynamics lines
#######################################################
COPY java_agent/ /opt/appd/java_agent
RUN chown -R root /opt/appd # in this example root is the user that runs the java app
RUN chmod -R 0775 /opt/appd
#######################################################

RUN chmod +x /startup.sh
RUN chmod +w /etc/resolv.conf

ADD java-services.jar java-services.jar

ENTRYPOINT ["/bin/bash", "/startup.sh"]
